#!/usr/bin/env ruby

require 'thor'
require 'cgem'

class CgemCLI < Thor
  default_command :status

  desc 'list', 'list current gem sources'
  def list
    puts Cgem.gem_sources
  end
  map ls: :list
  map '-l' => :list

  desc 'use SOURCE_KEY', 'use specified gem source'
  def use(source_key)
    source_key = source_key.to_s.strip
    source = Cgem.gem_sources[source_key]
    abort "Not fource source for #{source_key}" if source.nil?
    Cgem.set_gemrc_sources(source)
    Cgem::BundleMirror.new.set(source)
    puts "==set #{source} as default gem source"
  end

  desc 'status', 'get current gem status'
  def status
    puts Cgem.gemrc_sources
    puts Cgem::BundleMirror.new.get
  end

  desc 'current', 'get current gem source url'
  def current
    puts Cgem.gemrc_sources
  end

  desc 'version', 'show version'
  def version
    puts Cgem::VERSION
  end
  map '-v' => :version
  map '--version' => :version

  desc 'setup [SOURCE]', 'install by environment variable'
  def setup(source = nil)
    env_key = 'CGEM_KEY'
    source ||= ENV[env_key]
    abort "Not specify gem source or environment variable #{env_key}" if source.nil?
    abort "Please use source key in #{Cgem.gem_sources.keys}" if source.start_with?('http')
    use(source)
  end
end

CgemCLI.start
